// Auto-generated by wxEC 0.1.33 - 05/12/18 13:09:48
// Do not edit this file - it will be overwritten on next pass
// Make any necessary changes to the source file:
// D:\pkg\wx\MSVC2015\_3.1-2015\GitHubProjects\wxBup-Test\wxBupWhenDone.e

#ifndef _WXBUPWHENDONE_H
#define _WXBUPWHENDONE_H

#include "wx/string.h"

#define _EWhenDoneTypes_MAP_SIZE 6
//========================================================================
class EWhenDoneTypes
{
public:
	// EWhenDoneTypes::eWhenDone_Unknown,eWhenDone_DoNothing,eWhenDone_Exit,eWhenDone_Hibernate,eWhenDone_LogOff,eWhenDone_Shutdown,
	enum Enum
	{
		eWhenDone_Unknown =   0, // "unknown"
		eWhenDone_DoNothing, // "do nothing"
		eWhenDone_Exit, // "exit"
		eWhenDone_Hibernate, // "hibernate"
		eWhenDone_LogOff, // "logoff"
		eWhenDone_Shutdown, // "shutdown"
	};
	EWhenDoneTypes();
	virtual ~EWhenDoneTypes();
	inline int GetSize() { return m_iMapSize; };
	Enum operator=(int i);
	operator int () const;
	Enum operator=(const char* sz);
	bool operator==(const char* sz);
	operator const char* () const;
	static Enum AsEnum(const char* sz);
	static Enum AsEnum(int e);
	static const char* AsName(int e);
	static bool GetMap(int iIndex, int& iValue, const char*& szDescription);
	inline operator wxString () {return AsWxName(m_Enum); };
	static const wxString& AsWxName(int e);
	static bool GetMap(int iIndex, int& iValue, wxString& wsDescription);
	Enum m_Enum;
	class Map_t
	{
public:
		int iValue;
		char* szDescription;
		wxString wsDescription;
		Map_t( int iV = 0, char* szDesc = "", wxString wsDesc = _T("") )
		  {
		    iValue = iV;
		    szDescription = szDesc;
		    wsDescription = wsDesc;
		  };
	};
	static Map_t m_Map[];
	static const int m_iMapSize;
};
#endif // _WXBUPWHENDONE_H
// ------------------------------- eof ------------------------------
