// Auto-generated by wxEC 0.1.33 - 05/12/18 13:09:48
// Do not edit this file - it will be overwritten on next pass
// Make any necessary changes to the source file:
// D:\pkg\wx\MSVC2015\_3.1-2015\GitHubProjects\wxBup-Test\wxBupBagSizes.e

#ifndef _WXBUPBAGSIZES_H
#define _WXBUPBAGSIZES_H

#include "wx/string.h"

#define _EBupBagSizeTypes_MAP_SIZE 12
//========================================================================
class EBupBagSizeTypes
{
public:
	// EBupBagSizeTypes::eBagSize_Unknown,eBagSize_NoSplit,eBagSize_Custom,eBagSize_144MB,eBagSize_5MB,eBagSize_10MB,eBagSize_650MB,eBagSize_700MB,eBagSize_3_7GB,eBagSize_4_7GB,eBagSize_8_5GB,eBagSize_25GB,
	enum Enum
	{
		eBagSize_Unknown =   0, // "unknown"
		eBagSize_NoSplit, // "Single Volume, no split"
		eBagSize_Custom, // "Custom size"
		eBagSize_144MB, // "1.44 MB Floppy"
		eBagSize_5MB, // "5 MB Attachment"
		eBagSize_10MB, // "10 MB Attachment"
		eBagSize_650MB, // "650 MB CD"
		eBagSize_700MB, // "700 MB CD"
		eBagSize_3_7GB, // "3.7 GB DVD"
		eBagSize_4_7GB, // "4.7 GB DVD"
		eBagSize_8_5GB, // "8.5 GB DVD-DL"
		eBagSize_25GB, // "25 GB Blueray"
	};
	EBupBagSizeTypes();
	virtual ~EBupBagSizeTypes();
	inline int GetSize() { return m_iMapSize; };
	Enum operator=(int i);
	operator int () const;
	Enum operator=(const char* sz);
	bool operator==(const char* sz);
	operator const char* () const;
	static Enum AsEnum(const char* sz);
	static Enum AsEnum(int e);
	static const char* AsName(int e);
	static bool GetMap(int iIndex, int& iValue, const char*& szDescription);
	inline operator wxString () {return AsWxName(m_Enum); };
	static const wxString& AsWxName(int e);
	static bool GetMap(int iIndex, int& iValue, wxString& wsDescription);
	Enum m_Enum;
	class Map_t
	{
public:
		int iValue;
		char* szDescription;
		wxString wsDescription;
		Map_t( int iV = 0, char* szDesc = "", wxString wsDesc = _T("") )
		  {
		    iValue = iV;
		    szDescription = szDesc;
		    wsDescription = wsDesc;
		  };
	};
	static Map_t m_Map[];
	static const int m_iMapSize;
};
#endif // _WXBUPBAGSIZES_H
// ------------------------------- eof ------------------------------
